version: 0.0
os: linux

#EC2 내부에 있는 codedeploy agent가 이 파일을 읽고 실행을 진행한다.

#CodeDeploy 실행을 위해 필요한 yml파일
#S3에 source : / (모든 파일)을 EC2 : /home/ubuntu/cicd-test 이 경로로 옮기겠다는 의미
files:
  - source: /
    destination: /home/ubuntu/cicd-test

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

# 위에서 S3에게 파일을 EC2가 받아 온 후
# 어떤 명령어를 실행할지 정의한 파일의 경로를 적는다.
hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu

